name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: campus_access_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4
      # Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # Cache pip dependencies for faster builds
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Wait for MySQL service to be ready
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
              break
            fi
            sleep 2
          done
      # Initialize the database schema using database_setup.sql
      - name: Initialize DB schema
        run: |
          mysql -h127.0.0.1 -uroot -proot campus_access_db < database_setup.sql
      # Test database migration functionality
      - name: Test database migrations
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: campus_access_db
          DB_USER: root
          DB_PASSWORD: root
          SECRET_KEY: testsecretkey
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60
        run: |
          PYTHONPATH=. python scripts/init_db.py
      # Run comprehensive migration tests
      - name: Run migration tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: campus_access_db
          DB_USER: root
          DB_PASSWORD: root
          SECRET_KEY: testsecretkey
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60
        run: |
          PYTHONPATH=. python scripts/test_migrations.py
      # Verify database tables and data
      - name: Verify database setup
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: campus_access_db
          DB_USER: root
          DB_PASSWORD: root
        run: |
          # Check if all required tables exist
          mysql -h127.0.0.1 -uroot -proot campus_access_db -e "
            SELECT table_name FROM information_schema.tables 
            WHERE table_schema = 'campus_access_db' 
            ORDER BY table_name;
          "
          
          # Check if sample data was loaded
          mysql -h127.0.0.1 -uroot -proot campus_access_db -e "
            SELECT 'users' as table_name, COUNT(*) as count FROM users
            UNION ALL
            SELECT 'access_cards', COUNT(*) FROM access_cards
            UNION ALL
            SELECT 'rooms', COUNT(*) FROM rooms
            UNION ALL
            SELECT 'students', COUNT(*) FROM students
            UNION ALL
            SELECT 'professors', COUNT(*) FROM professors;
          "
      # Run the test suite with pytest
      - name: Run tests
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: campus_access_db
          DB_USER: root
          DB_PASSWORD: root
          SECRET_KEY: testsecretkey
          ALGORITHM: HS256
          ACCESS_TOKEN_EXPIRE_MINUTES: 60
        run: |
          PYTHONPATH=. pytest 